### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by zhixuanli** [youansheng/torchcv-seg#5]
When running this command `bash run_fs_deeplabv3_cityscape_seg.sh train 111`, the following errror occured.

> 2019-02-27 20:09:27,802 INFO    [trainer.py, 58] Params Group Method: None
Traceback (most recent call last):
  File "main.py", line 189, in <module>
    model.train()
  File "/home/oliver/PycharmProjects/torchcv-seg/segmentor/trainer.py", line 237, in train
    self.__train()
  File "/home/oliver/PycharmProjects/torchcv-seg/segmentor/trainer.py", line 132, in __train
    outputs = self.seg_net(inputs)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/torchcv-seg/models/nets/deeplabv3.py", line 80, in forward
    x = self.backbone(x_)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/torchcv-seg/models/backbones/resnet/resnet_backbone.py", line 105, in forward
    x = self.layer3(x)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/PycharmProjects/torchcv-seg/models/backbones/resnet/resnet_models.py", line 87, in forward
    out = self.relu(out)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 46, in forward
    return F.threshold(input, self.threshold, self.value, self.inplace)
  File "/home/oliver/anaconda3/envs/pytorchseg/lib/python3.7/site-packages/torch/nn/functional.py", line 625, in threshold
    return torch._C._nn.threshold(input, threshold, value)
RuntimeError: CUDA error: out of memory

Environment:
+ GPU : 2080Ti x 1
+ Pytorch 0.4.1
+ CUDA 9.2

I have set batchsize to 2 (when set to 1, the zero division error will occur), this error still exist.

Is there any solution for this?
Thank you so much!!

**Comment by donnyyou** [comment]
The GPU memory is not enough! Please use more GPUs for training or use torch BN instead.

**Comment by zhixuanli** [comment]
Thank you, I'll try to modify it to standard torch BN. :smiley:
